apiVersion: apps/v1
kind: Deployment
metadata:
  name: CONTAINER_NAME
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: CONTAINER_NAME
  template:
    metadata:
      labels:
        app: CONTAINER_NAME
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: CONTAINER_NAME
        image: CONTAINER_IMAGE
        ports:
        - containerPort: CONTAINER_PORT
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        envFrom:
        - configMapRef:
            name: moi-web-config     # non-sensitive values
        - secretRef:
            name: appdb-secret       # sensitive values
---
apiVersion: v1
kind: Service
metadata:
  name: CONTAINER_NAME
  namespace: test
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: CONTAINER_PORT
  selector:
    app: CONTAINER_NAME
